#
# Build, test and publish the package on release creation.
#
name: Publish Package to npmjs

on:
  release:
    types: [published]

jobs:
  publish:
    name: Publish to NPM registry
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        registry-url: https://registry.npmjs.org

    - run: npm i
    - run: npm run build
    - run: npm publish --access public
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
